name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta
      # N.x (maintenance release branches)
      - '[0-9]+.x'

concurrency:
  group: release-${{ github.ref }}

jobs:
  release:
    name: Reusable release workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/release_library.yml@testing_ref
    with:
      TIMEOUT: 30
      NODE_VERSION: 20.x
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_NONPROD
      IS_MONOREPO: true
      ENABLE_COVERAGE: false
    secrets: inherit