name: Release

on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta

jobs:
  release:
    name: Reusable release workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/release_library.yml@v1
    with:
      NODE_VERSION: 16.x
      PACKAGE_MANAGER: yarn
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_PROD
      IS_MONOREPO: true
    secrets: inherit
