name: Verify

on: [pull_request]

env:
  NODE_VERSION: 18.x

jobs:
  build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: lerna run build

      - name: Archive workspace on failure
        if: failure()
        run: zip -r workspace-files ./

      - uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: workspace
          path: workspace-files.zip

  notification:
    if: always()
    name: Send Workflow Notification
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0

      - uses: technote-space/workflow-conclusion-action@v3.0.3

      - uses: reside-eng/workflow-status-notification-action@v1.2.2
        with:
          current-status: ${{ env.WORKFLOW_CONCLUSION }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_PLATFORM_PROD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
